import type { Project } from '@/types';

export const PROJECTS: Project[] = [
  {
    id: '1',
    title: 'Ecommerce Sales Dashboard',
    slug: 'ecommerce-sales-dashboard',
    category: 'Dashboard Development',
    description:
      'Real-time sales tracking and revenue insights for a growing e-commerce brand. Integrated live order data, inventory levels, and customer acquisition metrics into a single Power BI dashboard.',
    cover_image: 'https://images.pexels.com/photos/265087/pexels-photo-265087.jpeg?auto=compress&cs=tinysrgb&w=800',
    tags: ['Power BI', 'SQL', 'Python', 'Data Analytics'],
    tech_stack: ['Power BI', 'SQL', 'Python', 'Excel'],
    outcome: 'Reduced reporting time by 80% and increased revenue visibility leading to a 23% improvement in inventory decisions.',
    featured: true,
    published: true,
    created_at: '2024-01-15T00:00:00Z',
  },
  {
    id: '2',
    title: 'Restaurant Analytics Dashboard',
    slug: 'restaurant-analytics-dashboard',
    category: 'Dashboard Development',
    description:
      'Menu optimization and customer behavior analysis for a multi-location restaurant chain. Combined POS data, customer surveys, and inventory records to identify top-performing menu items and peak hours.',
    cover_image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=800',
    tags: ['Tableau', 'Excel', 'Data Analytics', 'Customer Insights'],
    tech_stack: ['Tableau', 'Excel', 'Python', 'SQL'],
    outcome: 'Menu optimization led to 18% revenue increase and 12% reduction in food waste.',
    featured: true,
    published: true,
    created_at: '2024-02-20T00:00:00Z',
  },
  {
    id: '3',
    title: 'Netflix Analytics Dashboard',
    slug: 'netflix-analytics-dashboard',
    category: 'Business Intelligence',
    description:
      'Content performance and subscriber trends analysis using Netflix dataset. Built a comprehensive dashboard tracking viewer engagement, content ratings, genre performance, and subscription growth patterns.',
    cover_image: 'https://images.pexels.com/photos/4009409/pexels-photo-4009409.jpeg?auto=compress&cs=tinysrgb&w=800',
    tags: ['Power BI', 'Data Modeling', 'Streaming Analytics'],
    tech_stack: ['Power BI', 'Python', 'DAX', 'SQL'],
    outcome: 'Demonstrated content ROI patterns and identified underperforming genres, enabling strategic content investment decisions.',
    featured: true,
    published: true,
    created_at: '2024-03-10T00:00:00Z',
  },
  {
    id: '4',
    title: 'Student Performance Dashboard',
    slug: 'student-performance-dashboard',
    category: 'Data Analytics',
    description:
      'Learning progress and academic insights platform for an educational institution. Tracked student grades, attendance, assignment completion, and engagement metrics to identify at-risk students early.',
    cover_image: 'https://images.pexels.com/photos/256395/pexels-photo-256395.jpeg?auto=compress&cs=tinysrgb&w=800',
    tags: ['Tableau', 'Educational Data', 'Student Analytics'],
    tech_stack: ['Tableau', 'Python', 'SQL', 'Excel'],
    outcome: 'Early identification of at-risk students reduced dropout rates by 15% in the first semester.',
    featured: true,
    published: true,
    created_at: '2024-04-05T00:00:00Z',
  },
  {
    id: '5',
    title: 'Portfolio Website',
    slug: 'portfolio-website',
    category: 'Web Development',
    description:
      'Professional online presence and client engagement platform built with React, Node.js, and MongoDB. Full-stack MERN application with a custom CMS, contact system, and project showcase.',
    cover_image: 'https://images.pexels.com/photos/1779487/pexels-photo-1779487.jpeg?auto=compress&cs=tinysrgb&w=800',
    tags: ['React', 'Node.js', 'MongoDB', 'Full-stack'],
    tech_stack: ['React', 'Node.js', 'MongoDB', 'Express', 'Tailwind CSS'],
    outcome: '3x increase in client inquiries and significant improvement in professional credibility within the first month.',
    featured: false,
    published: true,
    created_at: '2024-05-12T00:00:00Z',
  },
  {
    id: '6',
    title: 'Business Website',
    slug: 'business-website',
    category: 'Web Development',
    description:
      'Brand visibility and lead generation website for a B2B services company. Clean, conversion-focused design with integrated contact forms, service pages, and SEO-optimized content architecture.',
    cover_image: 'https://images.pexels.com/photos/196645/pexels-photo-196645.jpeg?auto=compress&cs=tinysrgb&w=800',
    tags: ['HTML', 'CSS', 'JavaScript', 'SEO', 'Lead Generation'],
    tech_stack: ['HTML5', 'CSS3', 'JavaScript', 'WordPress'],
    outcome: 'Achieved first-page Google rankings within 60 days, generating consistent monthly inbound leads.',
    featured: false,
    published: true,
    created_at: '2024-06-01T00:00:00Z',
  },
];
